--SELECT 'YOUNGEST' AS TYPE, NAME, BIRTHDAY
--FROM worker
--ORDER BY BIRTHDAY ASC
--LIMIT 1;
--
--SELECT 'OLDEST' AS TYPE, NAME, BIRTHDAY
--FROM worker
--ORDER BY BIRTHDAY DESC
--LIMIT 1;
SELECT 'YOUNGEST' AS TYPE, NAME, BIRTHDAY
FROM worker
WHERE BIRTHDAY = (
    SELECT MIN(BIRTHDAY)
    FROM worker
)
UNION ALL
SELECT 'OLDEST' AS TYPE, NAME, BIRTHDAY
FROM worker
WHERE BIRTHDAY = (
    SELECT MAX(BIRTHDAY)
    FROM worker
);
